### ISSUE TITLE
Deserialize Option

### ISSUE THREAD

**Issue by Jemesson** [Kingson-de/marshal-serializer#2]
Hello. I'd like to know if you are going to accept your PR to include deserialize option?

**Comment by Kingson-de** [comment]
Hey, sure I can accept it. Is the solution sufficient to you? Have you tried it?
If yes, then give me some time to retest and to adjust the documentation.

**Comment by Jemesson** [comment]
Thanks @Kingson-de. I am looking for deserializing a JSON:API message. About your pull request it LGTM!

**Comment by Kingson-de** [comment]
@Jemesson alright merged #1 and tagged as v1.3.0
If you have any issues please let me know.
